site_name: DataDiggers | Construmix

repo_name: "2024.1-CONSTRUMIX"
repo_url: "https://github.com/mdsreq-fga-unb/2024.1-CONSTRUMIX"

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: lime

    - scheme: slate
      toggle:
        icon: material/toggle-switch
      primary: lime

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Documento de Visão: documentoVisao.md
